### ISSUE TITLE
Cannot open Sauce vUSB app because it's "malicious software" error

### ISSUE THREAD

**Issue by nadvolod** [wswebcreation/saucelabs-vusb-gui#1]
**Environment (please complete the following information):**
 - Client version: 0.1.6
 - OS version: 10.15.4

**Describe the bug**
When trying to open the application, we get an error from Mac saying that we can't open this software because it's downloaded from an external source and could be mailicious software.

**To Reproduce**
1. Download the release
2. Try to open it

**Expected behavior**
To just open

**Additional context**
However, there is a workaround. Go to Security & Privacy and click "Open Anyway
<img width="671" alt="Security___Privacy_and_Applications_and_Downloads" src="https://user-images.githubusercontent.com/2136245/79774416-c49bb980-8300-11ea-9d74-3c46689ff04b.png">
"

**Comment by wswebcreation** [comment]
@nadvolod 

Thanks for the ticket, it's open source so I don't have paid certificates. Care for a PR to update the docs with the steps you need to take?

**Comment by nadvolod** [comment]
cool @wswebcreation . I'll do it in the near future 👍

**Comment by wswebcreation** [comment]
Fixed, see https://github.com/wswebcreation/saucelabs-vusb-gui#cannot-open-sauce-vusb-app-because-its-malicious-software
