### ISSUE TITLE
Error "You environment has been set up properly, please check the Home page to see what needs to be fixed."

### ISSUE THREAD

**Issue by nadvolod** [wswebcreation/saucelabs-vusb-gui#2]
**Describe the bug**
"You environment has been set up properly, please check the Home page to see what needs to be fixed."
This isn't right.

**Expected behavior**
Your environment has NOT been set up properly, please check the Home tab to see what needs to be fixed.

**Comment by wswebcreation** [comment]
What...... 😨 , tnx

**Comment by wswebcreation** [comment]
Pushed the fix to my private repo, will be there in a next release, see 

![image](https://user-images.githubusercontent.com/11979740/80272425-718f8100-86c9-11ea-87d1-d5dea2553f77.png)

Closing this issue for now

**Comment by nadvolod** [comment]
@wswebcreation you also missed the "Your environment"

**Comment by wswebcreation** [comment]
changed it, thanks
