### ISSUE TITLE
Oops, Something went wrong while connecting to a device on Sauce Labs using Sauce VUSB Client

### ISSUE THREAD

**Issue by gauthampaimk** [wswebcreation/saucelabs-vusb-gui#3]
**Environment (please complete the following information):**
 - Client version: [e.g. 0.1.0] : Version 0.1.7 (0.1.7)
 - OS version: [Windows 10| OSX Mojave 10.14.6] :Mac OS Big Sur

**Describe the bug**
Try to connect to SauceVusbClient. The vUSB Server will be started successfully. Type the Tunnel identifier and try to access the Device Catalog and try to connect to a device which is available and find the Error.

**To Reproduce**
Try to connect to SauceVusbClient. The vUSB Server will be started successfully. Try to access the Device Catalog and try to connect to a device which is available and find the Error.

**Expected behavior**
If the device is available, it connects a virtual USB with the device which can be used in Android Studio for debugging, etc..

**Additional context**
The logs are attached.
[SauceVUSB_Error.txt](https://github.com/wswebcreation/saucelabs-vusb-gui/files/5694871/SauceVUSB_Error.txt)
<img width="1175" alt="Screen Shot 2020-12-15 at 3 17 17 PM" src="https://user-images.githubusercontent.com/50521640/102199252-69e74b80-3ee9-11eb-8792-ed9e2cd83efc.png">

**Comment by wswebcreation** [comment]
Hi @gauthampaimk 

Thanks for filing an issue, can you provide some more logs from the server itself by setting the logs on verbose mode and write the logs to a file and paste it here?

![image](https://user-images.githubusercontent.com/11979740/102201150-fe3fb700-3ec5-11eb-8df2-0269ee14ddb9.png)

**Comment by gauthampaimk** [comment]
Thanks for the quick response. Here are the logs
[Archive.zip](https://github.com/wswebcreation/saucelabs-vusb-gui/files/5695076/Archive.zip)

**Comment by wswebcreation** [comment]
Hi @gauthampaimk 

Are you behind a proxy/using a VPN?

**Comment by gauthampaimk** [comment]
@wswebcreation Yes, I am connected to a VPN. But, I am observing this error only when I provide a tunnel name and connect to a device and it works perfectly fine when the tunnel name is empty. But, this issue is prevailing from today.
JFYI, I am not on the latest sauce connect proxy for a tunnel creation that was released few days back.

**Comment by gauthampaimk** [comment]
@wswebcreation  It is somehow working now with the VPN and with and without the tunnel identifier as well!. Unfortunately it is not reproducible now. Will update if I see any issues..
