### ISSUE TITLE
No devices could be found error message

### ISSUE THREAD

**Issue by gauthampaimk** [wswebcreation/saucelabs-vusb-gui#6]
**Environment (please complete the following information):**
 - Client version: 0.5.0 
 - OS version: MacOS Big Sur 11.2.3

**Describe the bug**
Whenever you start the vUSB session and come to devices tab, the devices are empty with the error message."_No devices could be found. Reasons for this could be that you don't have private devices, please contact your Customer Success Manager at Sauce Labs_"
While the https://app.testobject.com/api/rest/v2/devices/available APK gives the response when inspected.

**To Reproduce**
1. Open SauceVusbClient
2. Start the vUSB client and come to devices tab.
3. See that the devices list are empty with error message.

**Expected behavior**
1. After starting vSUB client, devices as per the API keys should be visible.

**Additional context**
Attaching logs and a video
[server.log](https://github.com/wswebcreation/saucelabs-vusb-gui/files/6418826/server.log)

**Comment by wswebcreation** [comment]
Hi @gauthampaimk 

Thanks for this issue, this looks like an issue in the endpoint, it used to return `cloudType` per device stating if it was a private or public device. Because it's not there anymore it doesn't show any devices.

I'll contact Sauce Support and see what happens

**Comment by wswebcreation** [comment]
A fix has been deployed by Sauce Labs, I've tested it and it works.

Closed it for now

**Comment by gauthampaimk** [comment]
Thanks @wswebcreation for the timely response and resolution. The issue is fixed and I can now use the vUSB client with the devices provided by the organisation.

**Comment by wswebcreation** [comment]
@gauthampaimk 

By the way, SauceLabs released vUSB on the Unified Platform, so not using the legacy real device cloud anymore.

See https://docs.saucelabs.com/mobile-apps/virtual-usb

And https://github.com/saucelabs/saucelabs-vusb-app/releases for the new GUI
