### ISSUE TITLE
Unable to start server on sauce vusb GUI

### ISSUE THREAD

**Issue by divi243** [wswebcreation/saucelabs-vusb-gui#7]
**Describe your question with as much detail as possible.**

I am trying to use sauce labs gui tool, however i am unable to run the server it shows error - unable to locate java runtime. 
is there something i missed, canyou please guide me? i have java present and env is also set.
It shows green in first screen.

Error: The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

My java :
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 8.1.075)
SAP Java Server VM (build 8.1.075 10.0.2+000, Apr 30 2021 09:41:04 - 81_REL - optU - bsd amd64 - 6 - bas2:327393 (mixed mode))

**Environment (please complete the following information):**
 -  Version 1.0.1 (1.0.1)
 - OS version: OSX Mac OS BIG Slur -11.4 (20F71

**Comment by wswebcreation** [comment]
Hi @divi243 

Can you contact me at Sauce Labs so we can set up a meeting? It's my name and then `@saucelabs.com`

**Comment by wswebcreation** [comment]
Closing this one due to inactivity
